# Generated by Django 3.2 on 2022-02-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
    ]
